version: '3'
services:
  springboot-app:
    build: .
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/esho2_db?createDatabaseIfNotExist=true
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword  # Set the root password here
      - MYSQL_DATABASE=esho2_db
    ports:
      - "3306:3306"
